
 
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const GETBLOGS = "GETBLOGS"
export const GETBLOGSBYID = "GETBLOGSBYID"
export const LOADING = "LOADING"
export const ENDLOADING = "ENDLOADING"
export const GETPLANS = "GETPLANS"
export const GETUSER = "GETUSER"
export const SIGNUP = "SIGNUP"
export const SELECTPLAN = "SELECTPLAN"
export const UPGRADE = "UPGRADE"
export const AUTH_ERROR = "AUTH_ERROR"
export const CLOSE = "CLOSE"
export const AUTH_SUCCESS = "AUTH_SUCCESS"